research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

improve_survey:
  description: >
    You will receive:
    - The original survey (structured as a Survey Pydantic model)
    - A list of comments and suggestions for each question
    - A general comment and suggestion for the overall survey

    Your task is to:
    1. Return the original survey paired only with the comments (not the suggestions)
    2. Based on the comments and the suggestions to revise the survey
    3. Return both the annotated original and the revised survey as structured JSON.

  expected_output: >
    A JSON object with two parts:
    - original_with_comments: the original survey and feedback comments (only comments)
    - revised_survey: a revised version of the survey that addresses the comments and suggestions

  agent: survey_editor
