get_survey:
  description: >
    Retrieve both metadata and all collected responses for a published
    survey by its ID. Handle any necessary pagination to ensure completeness.
    Input key: survey_id
  tool: fetch_survey
  inputs:
    survey_id:
      description: "要获取的问卷 ID"
  outputs:
    survey:
      description: "问卷元数据（id, title, status, 等）"
    responses:
      description: "所有回答对象数组"
  expected_output: >
    A JSON object containing:
    - survey: an object with survey metadata (id, title, status, etc.)
    - responses: an array of all response objects submitted to the survey






    