post_survey:
  description: >
    Given a fully-designed survey definition JSON, deploy that survey to the
    configured survey platform via its API. Do not alter the survey content
    or structure—only handle the publication step.
    Input key: survey_definition
  tool: publish_survey
  inputs:
    survey_definition:
      description: "Typeform 表单定义 JSON"
  outputs:
    id:
      description: "新发布问卷的唯一标识符"
    title:
      description: "问卷标题"
    status:
      description: "发布状态（例如 “live”）"
    created_at:
      description: "发布时间戳"
  expected_output: >
    A JSON object confirming successful deployment, including at minimum:
    - id: the unique identifier of the newly published survey
    - title: the survey’s title
    - status: publication status (e.g. “live”)
    - created_at: timestamp of publication












