post_survey:
  description: >
    Given a fully-designed survey definition JSON, deploy that survey to the
    configured survey platform via its API. Do not alter the survey content
    or structure—only handle the publication step.
    Input key: survey_definition
  expected_output: >
    A JSON object confirming successful deployment, including at minimum:
    - survey_id: the unique identifier of the newly published survey
    - title: the survey’s title
    - status: publication status (e.g. “live”)
    - created_at: timestamp of publication















